### ISSUE TITLE
Setting up the OpenMesh radio 

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2016#10]
Set up the new wireless device for our team.

Documentation:
https://wpilib.screenstepslive.com/s/4485/m/13503/l/144986?data-resolve-url=true&data-manual-id=13503

**Comment by ChampD** [comment]
We can't actually do this until electrical gets the radio on a robot, and they are going to use the new radio on the competition bot, so i am going to set this to a later goal when we have the ability to do it.

**Comment by toastertaster** [comment]
what's the status of this?

**Comment by domi-a-philip** [comment]
Done! Finally after many attempts!
