### ISSUE TITLE
EVERYONE: Control system documentation reading

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2016#11]
Review the official documentation for the control system
https://wpilib.screenstepslive.com/s/4485/m/13503

As many people as possible should know this cover-to-cover by end of week 1.

**Comment by ChampD** [comment]
Additionally, everyone should read this: https://wpilib.screenstepslive.com/s/4485/m/13810/c/88685

**Comment by ChampD** [comment]
Argh, im gonna do this next meeting.
