### ISSUE TITLE
Remove Navx code warnings/errors.

### ISSUE THREAD

**Issue by ChampD** [Chantilly612Code/612-2016#130]

**Comment by WardBenjamin** [comment]
Did this ever get done? 

@Alexbay218 you are bad.

**Comment by Alexbay218** [comment]
I don't want to mess with the library without testing. Knowing navx, it would probably break.

**Comment by WardBenjamin** [comment]
@Alexbay218 Since the NavX isn't actually being used anywhere, this seems like a candidate for removal from the repository. If you aren't going to do anything with this, it should not be here.

**Comment by Alexbay218** [comment]
go ahead, no testing time for navx anyway.

**Comment by WardBenjamin** [comment]
Done! I have replaced and fixed the NavX library, and moved it into the libs folder.
