### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by Ahmad-Bamba** [Chantilly612Code/612-2016#135]
The code, specifically master and fix-workingcode encounter segmentation faults when ran. This needs to be fixed ASAP.

1. Make sure no buttons or hardware stuff have the same ids
2. Make sure we're not screwing around with memory pointers in a way that is dangerous.

We'll have to think outside the box for this one. Whoever assigns themselves, we all need to be working on this.

Edit: Tomorrow, I will try running the GNU Project Debugger (gdb) on ./FRCUserProgram on the roboRIO. This won't fix the problem, but it will be good to learn where it starts.

**Comment by toastertaster** [comment]
`OI.h` calls for a getButton, but I don't see it in the `OI.cpp`

**Comment by toastertaster** [comment]
Worth trying to check in `Robot::TeleopInit` if `invertcontrols` is a null pointer before calling `->Start()`

**Comment by toastertaster** [comment]
I also don't like how `OI.cpp` has variables servoPush and servoClamp and also class constructors servoPush() and servoClamp().  Need a better naming scheme.

**Comment by ChampD** [comment]
Fixed?
