### ISSUE TITLE
Making sure lifting the shooter doesn't move the target out of the field of view

### ISSUE THREAD

**Issue by ggodfrey** [Chantilly612Code/612-2016#138]
This is more of a reminder for me than anything. I dunno if we have a command that rotates the shooter to the right angle, but once we have this we need to make sure that we don't lift it to that point until the robot is centered on the target. My idea for doing this was having a boolean `isCentered` that becomes true when the haptic feedback is given and the robot is centered. It also checks if the lowest y values of the bounding box is below some value (say 5), and if it is, stop lifting the shooter until the boolean `isCentered` is true.

**Comment by toastertaster** [comment]
:+1:  for using markdown to use monospace fonts!
:tophat:

**Comment by WardBenjamin** [comment]
This should probably be revised because CAD did not inform us that the camera would not fit on the shooter itself, so it is now beside it. This will affect the distance and angle calculations for all three axes.

**Comment by WardBenjamin** [comment]
Not a problem anymore, camera not on the shooter itself.
