### ISSUE TITLE
Test shooter servo values

### ISSUE THREAD

**Issue by WardBenjamin** [Chantilly612Code/612-2016#139]
Right now the values in SetServoPosition are 0, .5, and 1, which are completely untested and probably will not work. These need to be tested.

**Comment by ChampD** [comment]
according to Alvin, the correct angles for the shooter lever are 15, 25, and 35 degrees.

**Comment by Ahmad-Bamba** [comment]
Maybe we should use SetAngle() then instead of Set(). Someone should just go through the code and change that to Alvin's values. Set() is kind of abstract anyways.

**Comment by ChampD** [comment]
Sounds good.

**Comment by WardBenjamin** [comment]
Something in this code doesn't work at all! Assigning this to Ahmad.

**Comment by Mister-GoodwinLu** [comment]
indeed.... even though i only participated within one competition, it seems apparent it is difficult for our robot to correctly execute the shooter servo.

**Comment by Ahmad-Bamba** [comment]
@Mister-GoodwinLu Nick showed my a mechanism that's going on the second bot that should rectify the problem mechanically.

**Comment by WardBenjamin** [comment]
We've replaced this with pneumatics.
