### ISSUE TITLE
Test DriveToDistance and implement turning functionality.

### ISSUE THREAD

**Issue by WardBenjamin** [Chantilly612Code/612-2016#145]
Ahmad has put together some code for driving in straight lines via encoders. This needs tested when the robot is un-bagged.

Additionally, we need to use the NavX code to write a command to turn by an angle. This should probably be done with at least some input from @Alexbay218?

**Comment by ChampD** [comment]
Drivetrain encoders are unverified and will probably never be used, we are switching all position tracking over to the NavX, which should allow us a larger degree of freedom as far as sensing robot tilt and speed. Therefore I am closing this.

**Comment by WardBenjamin** [comment]
Just as a note, the encoders have in fact been tested. The NavX will still also not help with distance tracking without a lot of work.
