### ISSUE TITLE
ShooterRotation falls over

### ISSUE THREAD

**Issue by Bobobalink** [Chantilly612Code/612-2016#149]
we will probably(tm) need to compensate for the shooter "falling over" due to belt slack. We might need to dynamically compensate for that.

**Comment by Mister-GoodwinLu** [comment]
that would be difficult. We would either need to have the belt adjust each time the shooter threatens to fall over (in case it happens again), or to adjust the shooter each time it falls.

**Comment by ChampD** [comment]
This is what PID loops are for, also, mechanical is going to significantly minimize this problem with shooter V2.0

If it ends up being an issue even with both of those factors, then I will re-add this issue.

**Comment by Bobobalink** [comment]
PID loops are going to make it significantly worse, not better. PID loops are good a correcting for a reliable and constant effect that is not greatly affected by position. When the shooter falls over, the PID loop is going to panic and while it might eventually settle, it's going to go crazy.

I'm more worried about bouncing, if the shooter is out and it gets jostled up and down quickly, the PID loop will try to react and end up setting the shooter to entirely the wrong position, so when it falls back down it'll be in the wrong place, then it'll have to go back up, which is all a terrible plan. We need to do something to correct for this, even if the PID eventually resettles, it might take a really long time and is always unnecessary.

We might be able to do something as simple as disabling PID if we detect a quick motion in one direction not caused by the motor, then we re-activate it after it's setted down.

**Comment by ChampD** [comment]
I don't know that I agree. Although the PID loop may get marginally annoyed, i think that so long as we use a reasonably large D value and a reasonably smallish I value, it should be mostly fine. I also don't think that jostling is gonna be a very big problem. Especially when the shooter is either all the way in or out, it will never jostle, as it will run up against the limit switches/mechanical stops. I do think that careful pid tuning will be required though. IDK, I could be wrong, this problem could be much bigger than I think it will be. So I'll leave this open though until we have the robot and can actually see for ourselves how bad the shooter floppiness is.

**Comment by WardBenjamin** [comment]
This was mostly fixed by mechanical when they modified the chain system and added a tensioner.
