### ISSUE TITLE
Jetson/DS NetworkTables communication

### ISSUE THREAD

**Issue by WardBenjamin** [Chantilly612Code/612-2016#153]
Before the first competition, we need to get the Jetson and DS communicating with NetworkTables and using FFmpeg's FFserver and FFplay executables to stream video from all three of our LifeCams.

**Comment by toastertaster** [comment]
Ambitious, good.  Make sure we do the simple stuff well also, before we need to do this high end stuff!

**Comment by WardBenjamin** [comment]
At this point, I finally got FFmpeg to compile on the Jetson (by specifying arch=arm and target-os=linux). @ZachPerkins1 is working on a Java program with the NetworkTables library to work on the communication aspects, while I work on getting the actual video streaming to work.

**Comment by Mister-GoodwinLu** [comment]
I'm not sure if this is still applicable since the first competition has already passed.

**Comment by WardBenjamin** [comment]
Since when has a competition going on ever stopped us!?!!?!?!? Our first autonomous setup was done by me during the first competition. This is still going on, albeit in a somewhat different manner. I'll have ZPerk update this tonight.

**Comment by ZachPerkins1** [comment]
As time goes on, it's important that we improve our robot, as other teams will improve as well. I'm not sure how clear this is (I.E. Who has actually been told this is happening), but we have switched to performing vision processing on the Jetson with OpenCV due to a significant reduction in latency. It is critical that we get cross Jetson-Robot communications running if we ever want a fully functional auto align.

**Comment by ZackAlfakir** [comment]
While there are many things that change throughout the seasons, learning how to use new technology is something that is held on to. During the 2012->early 2013 season, the team decided to learn how to use CAN, which is something that you guys are using to this day. If you were to get the Jetson to work with the robot, then that can be brought over to the next season.

**Comment by WardBenjamin** [comment]
We are no longer streaming the camera feeds because drivers decided that they didn't want them, but this now works using OpenCV for vision on the Jetson.

**Comment by WardBenjamin** [comment]
As a note, we have set up Robot<->Jetson NetworkTables communication, and Grey is working on https://github.com/Chantilly612Code/SmarterDashboard to improve on SmartDashboard.
