### ISSUE TITLE
Test Arm

### ISSUE THREAD

**Issue by Ahmad-Bamba** [Chantilly612Code/612-2016#154]
We need to make sure that ArmSetToPosition is working with PID, and ArmMove is working with the joystick D-Pad values. The PID stuff needs some serious testing (if mechanical will let us).

All the code to test is on fix-unbag

**Comment by WardBenjamin** [comment]
Are we actually targeting an arm anymore?

**Comment by Ahmad-Bamba** [comment]
I don't really think so. Closed until if they decide to stick it back on.
