### ISSUE TITLE
2016 Documentation

### ISSUE THREAD

**Issue by WardBenjamin** [Chantilly612Code/612-2016#16]
Last year we maintained our own copy of the WPILib documentation in a `gh-pages` branch. This year, we should do the same, and generate our own copy of the docs from the newest version of WPILib's Doxygen documentation.

**Comment by toastertaster** [comment]
@ggodfrey  how about I show you how to do this on Saturday?

**Comment by ggodfrey** [comment]
Alright, this is complete

**Comment by ggodfrey** [comment]
Added link, now it's complete, making pull request.
