### ISSUE TITLE
NavX Board created without issues

### ISSUE THREAD

**Issue by Alexbay218** [Chantilly612Code/612-2016#17]
Install navx board. (calibrate it)
Write code. (new subsystem)
Use navx board in code.
Requires Roborio to work.

**Comment by WardBenjamin** [comment]
I would suggest breaking this into multiple issues so that you can have a timeline of goals for this project.

**Comment by toastertaster** [comment]
@Alexbay218 @WardBenjamin is right, you can split this issue up to help focus your efforts.  Also make your issue title offer more insight into the specific thing you're doing :+1:

**Comment by Alexbay218** [comment]
Done, dev-navx has compling code if latest wpilib and navx lib is installed
