### ISSUE TITLE
Rewrite shooter actuator for the 6th time

### ISSUE THREAD

**Issue by Ahmad-Bamba** [Chantilly612Code/612-2016#173]
Mechanical has once again decided to change the kicker on the Robot. This time, it better work. Nonetheless, we need to write new code for the actuator. Word on the street is that we'll be using pneumatic to push the ball out of the shooter. Here's what the code needs to do:

* A branch has already been created dev-shooter_actuator. Check into it and you'll see that all the previous kicker code has been deleted

* Create a subsystem for the shooter actuator

* Create a compressor ([Relay](http://first.wpi.edu/FRC/roborio/release/docs/cpp/classRelay.html)) object in RobotMap. Set to kForward when the robot is enabled and when Get() does not return 1. Set it to kOff when Get() returns 1

* Create a [solenoid](http://first.wpi.edu/FRC/roborio/release/docs/cpp/classSolenoid.html#a913e4530ea804c7c0e3baf2458b4dee3) object. Set to true when the A button on the joystick is pressed and false when it is not

* Put dummy ports in Ports.h

Extra hints:

* The relay pressure checking should be handled in Robot.cpp.

* The solenoid values should only be changed in commands 

* Have a default command turn the solenoid off and another command that interrupts the default command turning the solenoid on. Assign the later to the A button on gunner in OI.

*  Look at the [2014](https://github.com/Chantilly612Code/612-2014) pneumatic code for further help

I expect all of this to be done through a command based structure. We need it soon, like, by Saturday.

**Comment by ggodfrey** [comment]
To add to this, for the dummy ports in Ports.h make sure you add a comment to change the values later to what they should be.

**Comment by WardBenjamin** [comment]
Already done.

**Comment by Ahmad-Bamba** [comment]
When did you do this?

**Comment by WardBenjamin** [comment]
Today!

**Comment by Ahmad-Bamba** [comment]
Just FYI the compressor has its own class now, so use that maybe
