### ISSUE TITLE
Change all examples of include guards to pragma once

### ISSUE THREAD

**Issue by ChampD** [Chantilly612Code/612-2016#174]
In EVERY .H FILE in the repo, replace the 

    #ifndef WHATEVER
    #define WHATEVER
    // code
    #endif WHATEVER

with

    #pragma once
    // code as before

Literally just delete the include guards and add the `#pragma once` to the beginning of the file. 

I want this done by a new programmer.

**Comment by WardBenjamin** [comment]
:+1:  This looks much better and I've been doing it in the code I write.

**Comment by Ahmad-Bamba** [comment]
I've been thinking about this myself. My only complaint is that Eclipse automatically generates include guards, so it might be a pain when adding future files

**Comment by WardBenjamin** [comment]
This can be changed in Eclipse. The setting is located at `Window/Preferences/C++/Code Templates/Files/C++ Header File/Default C++ header template`.

**Comment by ChampD** [comment]
@DavidRow Read my pull request comments.

**Comment by ChampD** [comment]
Now it is actually finished. Good job.
