### ISSUE TITLE
Auto breaching

### ISSUE THREAD

**Issue by ChampD** [Chantilly612Code/612-2016#176]
As part of our autonomous routine, we need to make sure that our robot is actually over the defense before we can fire our ball into the high goal. As such, we need to use the NavX accelerometer and gyro data to make sure that the robot is positioned past the defense and level on the ground (i.e. past the defense). 

So make a command that drives across a defense and actively keeps the bot driving straight and increases the motor speed to the wheels if the gyroscope is not showing a forward movement (i.e. the bot is stuck).

**Comment by ZackAlfakir** [comment]
Not enough labels

**Comment by WardBenjamin** [comment]
@ZackAlfakir Okay!

**Comment by WardBenjamin** [comment]
I may actually do this but Ahmad might want a new programmer to try this instead.

**Comment by ZackAlfakir** [comment]
haha alright. I heard its **Difficult Coding** though

**Comment by Bobobalink** [comment]
That's just Ben being salty about trying to engage more programmers, don't acknowledge it.
Some combination of everyone will be working on this once auto-align is a real thing... It'll be soon, except that auto-align is cursed and something more pressing goes horribly wrong every time we try to test it.

**Comment by toastertaster** [comment]
mother of god

**Comment by ChampD** [comment]
I... um.. this was not the original intent.

**Comment by ChampD** [comment]
There we go, that's what I intended.

**Comment by toastertaster** [comment]
okay so who is really going to do the work on this?

**Comment by Ahmad-Bamba** [comment]
Done and implemented successfully
