### ISSUE TITLE
Fix Travis CI Build process

### ISSUE THREAD

**Issue by WardBenjamin** [Chantilly612Code/612-2016#19]
Right now the Travis CI build process is failing because of some change in WPILib's folder structure, as far as I can tell. 

Related #12, #13, #18.

**Comment by toastertaster** [comment]
@WardBenjamin the latest version is now http://first.wpi.edu/FRC/roborio/release/eclipse/plugins/edu.wpi.first.wpilib.plugins.cpp_0.1.0.201601151923.jar

can you fix this again?

**Comment by WardBenjamin** [comment]
Updating the WPILib version does fix the WPILib-related errors as expected, but as I thought there are still more issues. Partial build log follows:

    W: Failed to fetch http://ppa.launchpad.net/wpilib/toolchain/ubuntu/dists/precise/main/source/Sources  404  Not Found
    W: Failed to fetch http://ppa.launchpad.net/wpilib/toolchain/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found
    W: Failed to fetch http://ppa.launchpad.net/wpilib/toolchain/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package frc-toolchain

Aka, we have a small issue. From what I can tell, this is because Travis is using Ubuntu 12.04.5 LTS (aka Precise), and not Trusty (Ubuntu 14.04.3 LTS). This means that since the compiler only has versions compiled for 14.04, 15.04 (which is soon being marked as obsolete), and 15.10, which is also nearing EOL, the Ubuntu versions do not match. This results in errors when trying to find: http://ppa.launchpad.net/wpilib/toolchain/ubuntu/dists/**precise**/main because there are no available versions for Precise.

I have a possible fix for this that I will test.

**Comment by WardBenjamin** [comment]
Fixed!

I went through a ton of possible changes then finally found a way to force Travis to use Trusty as the build environment. The build now passes. 

This should also fix https://github.com/Chantilly612Code/612-2016/issues/15.
