### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by ZackAlfakir** [Chantilly612Code/612-2016#3]
In order to upgrade to their new system, all commands must be done without root. This means that instead of installing the toolchain, it needs to be downloaded and then linked.

I also noticed a few more improvements that could be done:
Everything needed for FRC Travis CI could be bundled together easily.
Version of wpilib needs to be updated constantly and manually. There must be a better way.
Passing binaries could be uploaded somewhere so there is always an up-to-date binary without people freaking out about a broken compiler.

**Comment by WardBenjamin** [comment]
Alright, I've open-sourced the repository and migrated the CI system to the open-source version of Travis. Our build badge in the README is also working.

I think the only step left is to wait for them to add the apt source so that we can migrate to the new build system that Travis CI is using.

**Comment by toastertaster** [comment]
Can you disable the deploy event work until we have something meaningful there?  Seems a shame to have build errors for no reason.

**Comment by toastertaster** [comment]
@WardBenjamin @ZackAlfakir is this done?

**Comment by ChampD** [comment]
@WardBenjamin @ZackAlfakir actually though, is this done?
