### ISSUE TITLE
Write Drivetrain DriveJoystick command.

### ISSUE THREAD

**Issue by ChampD** [Chantilly612Code/612-2016#33]
Use the wiki docs for more info. Note: This one is rather hard, compared to the others.

**Comment by Mister-GoodwinLu** [comment]
hmm.... we'll need to decide what kind of joystick to use, obviously. Any ideas?

**Comment by Jeffrey-Wang** [comment]
Deadzone should be defined as when 
sqrt((x-axis value) ^2 + (y-axis value) ^2) < 0.1 
in order to make it circular

**Comment by Jeffrey-Wang** [comment]
Is sqrt an efficient algorithm in code? if it's too complex or slow, maybe just put
(x-axis)^2 + (y-axis)^2 < 0.01

**Comment by Jeffrey-Wang** [comment]
Or maybe there should be a deadzone along both axis, so one can input a pure throttle or rotation without causing the other. Don't think this circular stuff matters if we do that, just implement the deadzones on each axis value individually.

**Comment by ChampD** [comment]
So whoever is doing this should assign it to themselves by clicking the "Assignee" tab on the right side of the issue and selecting their name. Also, the way the drive system works, there should be a dead zone on both axes individually. (i.e. if axis one is 0.08 and axis two is 0.6, then the output to the motors should be 0 and 0.6, not 0 and 0). Finally, when i refer to Joystick, i am talking about the Joystick class which can be found here: http://first.wpi.edu/FRC/roborio/release/docs/cpp/classJoystick.html

**Comment by Jeffrey-Wang** [comment]
Is this command called "within" the Drivetrain class? 
i.e. I'm not sure how to call SetTankDrive(0,0), does it need to be used on an object or can it be called by itself?

**Comment by ChampD** [comment]
SetTankDrive, SetArcadeDrive, and SetManualDrive are all methods that will be put in the Drivetrain subststem file. They will be called from  commands. Commands are called in a few different ways. They can be called automatically by a button press, they can be called by a command group, or they can be called manually by calling the Command's Start() method. More info on how this works can be found here: http://wpilib.screenstepslive.com/s/4485/m/13810/l/241904-running-commands-on-joystick-input

**Comment by Jeffrey-Wang** [comment]
I'm going to attempt this in branch feature-DriveJoystick. Feel free to make commits, don't know if I can figure it out myself.

**Comment by Jeffrey-Wang** [comment]
Just read DriveJoystick more thoroughly. It's taking two separate joysticks y-axises for individual control of each side, not a single joystick for rotation and throttle. That will make this easier...

**Comment by Jeffrey-Wang** [comment]
I don't know where to start anymore. I know where the "driver" shared pointer is in OI, but it only seems to represent one joystick, with one Y-axis.

**Comment by Jeffrey-Wang** [comment]
I believe there is a problem with OI.getDriver() and OI.getGunner(). They are public, but return pointers to private variables which are inaccessible when you need to call the public methods.

**Comment by ChampD** [comment]
@Jeffrey-Wang Check out my comments on the pull request you made that I refused. The bulk of your code was really good, just a few minor problems that I will help you fix.
