### ISSUE TITLE
Write DriveToDefense Drivetrain Command

### ISSUE THREAD

**Issue by ChampD** [Chantilly612Code/612-2016#35]
Use wiki doc for more details.

**Comment by toastertaster** [comment]
@Ahmad-Bamba maybe you can show several students how to write a command? We can do several of the DriveTrain ones this week, if so.

**Comment by Ahmad-Bamba** [comment]
Yeah sure. I'm 90% sure I can make the meeting Monday so we can start there.

**Comment by toastertaster** [comment]
:+1: :bow:

**Comment by Mister-GoodwinLu** [comment]
hm. mine might need some work but it compiles...for now.

**Comment by Ahmad-Bamba** [comment]
This won't be done until we get a more concrete status on vision.

**Comment by Ahmad-Bamba** [comment]
This is seriously so outdated.
