### ISSUE TITLE
Navx Library and Board Improvement

### ISSUE THREAD

**Issue by Alexbay218** [Chantilly612Code/612-2016#46]
Implement features in Navx subsystem (currently only a wrapper)
Delete robot.cpp changes and improve Navx subsystem.
Solve Navx board issues (not working reliably).

**Comment by Alexbay218** [comment]
Solve Navx unreliability and fully tested. Case installed on navx board. Further improvements are to be handed off to Paola.

**Comment by Mister-GoodwinLu** [comment]
well done.

**Comment by Alexbay218** [comment]
Paola, look at navx wiki for help

**Comment by ChampD** [comment]
Done!
