### ISSUE TITLE
Joystick button map

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2016#48]
We need to document the necessary joystick buttons that we'll have. 

- [x] make a new wiki page for Joystick buttons
- [x] discuss with drive team current button needs.  Update wiki page
- [x] are we using an xbox controller or a flight stick?
- [x] how many joysticks are we planning on using?
- [x] post a diagram of the joystick button mapping to the wiki page
- [x] make edits to `OI.cpp` and `OI.h` files as necessary

**Comment by Mister-GoodwinLu** [comment]
well, xbox is definitely preferable to joystick joystick. It offers more options and versatility.

**Comment by WardBenjamin** [comment]
I've edited your comments, but we usually call a "joystick joystick" a flight stick.

Also, Goodwin, sometimes a flight stick is better. We have used them in past years and might actually be better for the gunner so they can aim the shooter more easily.

**Comment by Alexbay218** [comment]
I'll do this along with smooth joystick. Who is the drive team this year?

**Comment by Alexbay218** [comment]
wiki information is incorrect

**Comment by WardBenjamin** [comment]
@Alexbay218 I've got a partial implementation of joystick smoothing that I'm working on. I think you're experienced enough with git that we can work on things in the same branch, so go ahead and start working on whatever else.

**Comment by Mister-GoodwinLu** [comment]
just curious, how is the amount of joysticks not obvious? In what case would two or more be necessary? (Or if you feel insane enough, try justifying zero joysticks)

**Comment by ChampD** [comment]
I  think this is done??>! Im closing it.
