### ISSUE TITLE
DriveTrain flip orientation

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2016#49]
We've been asked to have a joystick flip so we can change the meaning of the forward/reverse directions.

- [ ] what are our options to accomplish this? flip joystick axes? invert motor outputs?
- [ ] provide recommendation to Travis for further guidance.

**Comment by Mister-GoodwinLu** [comment]
I think inverting would be alright. Flipping the axes would be confusing and have an unknown effect.

**Comment by ChampD** [comment]
As for more details as to what this means, this should all go into the DriveJoystick Command. (Which is not done yet). We are going to be flipping the controller input in such a way that the front of the robot becomes the "back" as far as the drivers are concerned. A related goal is for the team is to make the camera output to the drivers station dynamically changes cameras depending on the current front side of the robot.

**Comment by Jeffrey-Wang** [comment]
I think I'll try, but I think the part that goes in Drivetrain will have to be activated by other commands, or some other source.

**Comment by ChampD** [comment]
So here is what I want done. make a static boolean in robotmap called isRobotReversed. Then make two methods in drivetrain called getDriveReversal and setDriveReversal. getDriveReversal will return isRobotReversed. setDriveReversal will take a boolean value and set isRobotReversed to that variable. Once you have done this, then in every drivetrain method, reverse the sign of the outputs from the methods to RobotDrive if the isRobotReversed variable is set to true.

**Comment by Jeffrey-Wang** [comment]
I think I have it done, but I'm getting some errors. Not enough time to solve this meet.

**Comment by ChampD** [comment]
Ok, so i have realized that the way i previously said to make the drive reversal work is dumb and stupid. I have thought of a different way that is much better. Just use the GetInverted and SetInverted methods in Talon.cpp. Make a command that simply retrieves all the GetInverted values for all the motors, and then inverts them and puts them into the SetInverted method for each motor. Boom. Just make a command that does that. Call it InvertMotors.cpp

**Comment by WardBenjamin** [comment]
So you're doing exactly what I suggested, @ChampD? Knew you would come around to my way of thinking eventually. :D

**Comment by Alexbay218** [comment]
David created code for this.
