### ISSUE TITLE
EVERYONE: Install software on your personal computers

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2016#6]
Everyone with their own computer must complete

Champ gave guidance on how to do this:
http://www.chantillyrobotics.org/forum/index.php/topic,958.0.html

Also:
https://wpilib.screenstepslive.com/s/4485/m/13503/l/145002-installing-eclipse-c-java

Leave a comment after you complete so we can inventory.

**Comment by ChampD** [comment]
You scrubs, get on this!!!

**Comment by ChampD** [comment]
I am confident that enough people have done this that i can close it. Even if there are some stragglers who have not installed everything, I can help them out myself.
