### ISSUE TITLE
PassDefense command

### ISSUE THREAD

**Issue by Ahmad-Bamba** [Chantilly612Code/612-2016#65]
For the code, we need a command that when a button on the driver is pressed, the robot can pass the defense in front of it. This requires a lot of vision and advanced level stuff, but the basics can still created now.

For this, a command needs to be made that, depending on the value of an enum, executes a different method to breech all the defenses. The enum values should be set to all the types of defenses. The methods in drivetrain would be the various ways to cross all the defenses. 

**This may render the BreachDefense commands obsolete.** Keep this in mind.

Edit:

This is now **BreachAuto**
1. Make enum Defenses in Robot.h
2. In Execute of BreachAuto, make a switch statement for all values of Defenses including NONE
3. The switch statements should call methods in Drivetrain. Those methods should be designed to pass the defenses.

Defense list:
* None
* Portcullis
* Cheval de Frise
* Moat
* Ramparts
* Drawbridge
* Sally Port
* Rock Wall
* Rough Terrain
* Low Bar

**Comment by AbDen** [comment]
We'll try to work on the basics

**Comment by WardBenjamin** [comment]
This should be made a part of https://github.com/Chantilly612Code/612-2016/issues/176.
