### ISSUE TITLE
Write ArmSet command

### ISSUE THREAD

**Issue by ChampD** [Chantilly612Code/612-2016#75]
see wiki.

**Comment by dnimishe** [comment]
I'm gonna work on this

**Comment by Mister-GoodwinLu** [comment]
excellent, excellent. A good challenge indeed.

**Comment by Jeffrey-Wang** [comment]
So I finished this, accidentally forgot to assign it to myself. Branch is feature-armset-alt.

**Comment by ChampD** [comment]
Finished in #92
