### ISSUE TITLE
Change CANTalons in RobotDrive to Talons

### ISSUE THREAD

**Issue by ChampD** [Chantilly612Code/612-2016#76]
We are using Talon SR's this year for the drive train in RobotDrive. This is because 1: we do not have enough Talon SRX's for both robots and 2: we are not using any of the SRX features on the drivetrain.

It should be as easy as changing CANTalon to Talon in RobotMap.cpp.

**Comment by Mister-GoodwinLu** [comment]
what a shame, since the compiling takes absurdly long even if the actual process is easy.
