### ISSUE TITLE
Set up RoboRIO

### ISSUE THREAD

**Issue by toastertaster** [Chantilly612Code/612-2016#8]
1. Find Spare RoboRIO
1. Install updated RoboRIO image from National Instruments (needs FRC utilities)
1. Test uploading code from Eclipse

Documentation: https://wpilib.screenstepslive.com/s/4485/m/13503
https://wpilib.screenstepslive.com/s/4485/m/13503/l/273817-updating-your-roborio-firmware
https://wpilib.screenstepslive.com/s/4485/m/13503/l/144984-imaging-your-roborio

Note: This task will be quite a bit of work.  For example, this needs quite a bit of additional hardware to power the roborio and such.

**Comment by WardBenjamin** [comment]
This has been done already by me pre-season except for the updated image. I can do this on Monday.

**Comment by toastertaster** [comment]
With so many new people, you get to help but not do this one :exclamation:

**Comment by WardBenjamin** [comment]
@toastertaster okay! Someone else can do this then.

**Comment by ChampD** [comment]
Yeah, this is going to have to get done when electrical finishes the board.

**Comment by ggodfrey** [comment]
!Zach says it's done.
