### ISSUE TITLE
Kitbot drive correction and Controls

### ISSUE THREAD

**Issue by Alexbay218** [Chantilly612Code/612-2016#95]
Currently the kitbot cannot drive straight because of belt tension issues. Using navx (not encoders), auto-correct the kitbot and drive in a straight line.

dev-kitbot: [![Build Status](https://travis-ci.org/Chantilly612Code/612-2016.svg?branch=dev-kitbot)](https://travis-ci.org/Chantilly612Code/612-2016)

- [x] Navx code on dev-kitbot branch
- [x] Fix kitbot motor issues
- [x] Deploy code to kitbot
- [ ] Test auto-correction code
- [ ] Talk to drive team for control and implement on kitbot for testing (and practice).

Smooth Joystick in issue #48 will be used.

**Comment by Jeffrey-Wang** [comment]
Note: latest commit "change test2 to current src folder" in branch dev-kitbot added the ExampleSubsystem, ExampleCommand, and CommandBase. I think they should probably be deleted.

**Comment by WardBenjamin** [comment]
Is there any progress on this?

**Comment by WardBenjamin** [comment]
Since we no longer have the kitbot, this code should be incorporated into the current auto work as per https://github.com/Chantilly612Code/612-2016/issues/176.
