### ISSUE TITLE
ShooterRotation ShooterJoystick command

### ISSUE THREAD

**Issue by ChampD** [Chantilly612Code/612-2016#99]
make it. use the wiki docs.

**Comment by AbDen** [comment]
@ DavidFiumano  Please merge your changes (You said some time ago you already finished the joystick) - Goodwin Lu

**Comment by Mister-GoodwinLu** [comment]
@DavidFiumano mentioning you twice just in case your brain has gone haywire from working too much and you go crazy from forgetting something so simple.
